######### AUTH ########

### SignUp

POST http://localhost:3001/api/auth/register/
content-type: application/json

{
    "name": "Ivetta Leana",
    "email": "ivetta@mail.com",
    "password": "12345",
    "phone": "(111) 111-1111"
}


### SignIn

POST http://localhost:3001/api/auth/login/
content-type: application/json

{
    "email": "ivetta@mail.com",
    "password": "12345"
}


### SignOut

GET  http://localhost:3001/api/auth/logout/
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNmUyNTBhM2ZjOGNkZmQ5YjhmMGNiYSIsImlhdCI6MTY2ODE2MzE2OSwiZXhwIjoxNjY4MjA2MzY5fQ.irJG3mpkyaueVrcZEEqMmfto4SUiEqnCtOoQ01SahEY

######### NOTICES ########

### ListNotices

GET http://localhost:3001/api/notices/


### ListNoticesByCategory

GET http://localhost:3001/api/notices/categories/lost


### GetNotiseById

GET http://localhost:3001/api/notices/636b84c036eeb1ed7a216b8f