######### AUTH ########

### SignUp

POST https://petly-project-goit.herokuapp.com/api/auth/register/
content-type: application/json

{
    "name": "Ivetta Leana",
    "email": "ivetta@mail.com",
    "password": "12345",
    "phone": "(111) 111-1111"
}

###

POST https://petly-project-goit.herokuapp.com/api/auth/register/
content-type: application/json

{
    "name": "Xara Zeng",
    "email": "zeng@mail.com",
    "password": "54321",
    "phone": "(111) 111-1111"
}


### SignIn

POST https://petly-project-goit.herokuapp.com/api/auth/login/
content-type: application/json

{
    "email": "ivetta@mail.com",
    "password": "12345"
}

###

POST https://petly-project-goit.herokuapp.com/api/auth/login/
content-type: application/json

{
    "email": "zeng@mail.com",
    "password": "54321"
}


### SignOut

GET  https://petly-project-goit.herokuapp.com/api/auth/logout/
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNzAyMTU4NzQ3NWQwMDdmYjg1ZDNkNCIsImlhdCI6MTY2ODc1NzU0OCwiZXhwIjoxNjY4NzYxMTQ4fQ.jl-hATu7TpwqpRzE9M8GcP-lxYcmkPDTqN6tBYpG2JM


######### NEWS ########

GET https://petly-project-goit.herokuapp.com/api/news/

#########

GET https://petly-project-goit.herokuapp.com/api/news/search/:query/

######SERVICES-SIDEBAR############
GET  https://petly-project-goit.herokuapp.com/api/services

######### NOTICES ########

### ListNotices

GET https://petly-project-goit.herokuapp.com/api/notices/

### ListNoticesByQuery

GET https://petly-project-goit.herokuapp.com/api/notices/?category=sell&query=cat


### ListNoticesByCategory

GET https://petly-project-goit.herokuapp.com/api/notices/categories/sell?page=1&limit=8


### GetNotiseById

GET https://petly-project-goit.herokuapp.com/api/notices/63714b717d632b76b6544769


### ListUserNotices

GET https://petly-project-goit.herokuapp.com/api/notices/own?favorite=true
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNzAyMTU4NzQ3NWQwMDdmYjg1ZDNkNCIsImlhdCI6MTY2ODg1Mjc3NywiZXhwIjoxNjY4ODU2Mzc3fQ.kC5_ZtWBfBp84uV-XwwTtQOuCMnRsgF2PlP0agmUKso



### AddNotice

POST https://petly-project-goit.herokuapp.com/api/notices/
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNzAyMTU4NzQ3NWQwMDdmYjg1ZDNkNCIsImlhdCI6MTY2ODg1NjgwOCwiZXhwIjoxNjY4ODYwNDA4fQ.8d9jba_jexZC-2WVXy_28kKBfgZjlgVbKD9HgDWNAAY

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="data"

{  
    "category": "sell",
    "title": "Cute cat looking for a good family",
    "description": "Very nice and polite cat hopes to find home and loving family to become a part of",
    "name": "Napoleon",
    "location": "Dnipro",
    "sex": "male",
    "price": 1200,
    "comments": "Please, feel free to contact me at the weekend"
}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="cat.jpg"
Content-Type: image/png

< ../temp/cat.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

POST https://petly-project-goit.herokuapp.com/api/notices/
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNzczODA2ZjkyNjkyNTViNmE5ZmU3MiIsImlhdCI6MTY2ODc1OTk2OSwiZXhwIjoxNjY4NzYzNTY5fQ.A0GCRMhSsL6az5opTa43RA4IropPd_JK3d9kECo2IHs

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="data"

{   
    "category": "sell",
    "title": "Cute dog looking for a good family",
    "description": "Very nice and polite dog hopes to find home and loving family to become a part of",
    "name": "Nora",
    "location": "Lviv",
    "sex": "female",
    "price": 1000,
    "comments": "Please, feel free to contact me at the weekend"
}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="cat.jpg"
Content-Type: image/png

< ../temp/dog.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

POST https://petly-project-goit.herokuapp.com/api/notices/
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNzczODA2ZjkyNjkyNTViNmE5ZmU3MiIsImlhdCI6MTY2ODc1OTk2OSwiZXhwIjoxNjY4NzYzNTY5fQ.A0GCRMhSsL6az5opTa43RA4IropPd_JK3d9kECo2IHs

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="data"

{   
    "category": "sell",
    "title": "Cute bird looking for a good friend",
    "description": "Very nice and polite bird hopes to find home and loving family to become a part of",
    "name": "Patty",
    "location": "Kyiv",
    "sex": "male",
    "price": 100,
    "comments": "Please, feel free to contact me at the weekend"
}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="cat.jpg"
Content-Type: image/png

< ../temp/bird.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### UpdateFavorites 

PATCH https://petly-project-goit.herokuapp.com/api/notices/favorites/63714b717d632b76b6544769
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNzAyMTU4NzQ3NWQwMDdmYjg1ZDNkNCIsImlhdCI6MTY2ODg1Mjc3NywiZXhwIjoxNjY4ODU2Mzc3fQ.kC5_ZtWBfBp84uV-XwwTtQOuCMnRsgF2PlP0agmUKso

{   
    "favorite": true
}

### RemoveNotice

DELETE https://petly-project-goit.herokuapp.com/api/notices/63714b717d632b76b6544769
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNzAyMTU4NzQ3NWQwMDdmYjg1ZDNkNCIsImlhdCI6MTY2ODc1NzU0OCwiZXhwIjoxNjY4NzYxMTQ4fQ.jl-hATu7TpwqpRzE9M8GcP-lxYcmkPDTqN6tBYpG2JM
